### ISSUE TITLE
latency benchmark?

### ISSUE THREAD

**Issue by 9throok** [edwko/OuteTTS#1]
I have tried running the model on A100 but the latency I recorded is around 2.5 secs for a simple text like "Hello, am I working?".

I have used the code snippet provided in the docs. Here is the reference:

```
from outetts.v0_1.interface import InterfaceHF, InterfaceGGUF

# Initialize the interface with the Hugging Face model
interface = InterfaceHF("OuteAI/OuteTTS-0.1-350M")

# Or initialize the interface with a GGUF model
# interface = InterfaceGGUF("path/to/model.gguf")

# Generate TTS output
# Without a speaker reference, the model generates speech with random speaker characteristics
output = interface.generate(
    text="Hello, am I working?",
    temperature=0.1,
    repetition_penalty=1.1,
    max_lenght=4096
)

# Play the generated audio
output.play()

# Save the generated audio to a file
output.save("output.wav")
```

The above mentioned 2.5 secs was the time for `interface.generate` and no other steps included. 

Is this model really this slow, or is there some mistake?

**Comment by tushar-31093** [comment]
It is surely slow. But seems fine as a rudimentary model that can run locally and has a but of quality.

**Comment by edwko** [comment]
This might be related to #26. You can try the suggestions mentioned there. For better performance, you could also check out the `llama.cpp` and `exllamav2` implementations.
