### ISSUE TITLE
Deploying with LMStudio

### ISSUE THREAD

**Issue by tushar-31093** [edwko/OuteTTS#13]
Hi Team,
I am already using LMStudio and OLLAMA for model deplyments. Given this model is LMCPP compatible and uses that. How can this model be deplyment, hosted and used with LMStudio or OLLAMA. It is merely about model deplyment I suppose as we anyways have to wrap it around Whisper for text ectraction from the audio and pass them both for voice cloing to the api built by wrapping your code.

Help here would be highly appretiated. Really interesting to see it work.

**Comment by edwko** [comment]
Hey,
The model itself can be hosted, and you could use an API to integrate it. You might consider creating a similar class to [InterfaceGGUF](https://github.com/edwko/OuteTTS/blob/d90c645f56c9567ba91bea15f63950320e422ea7/outetts/v0_1/interface.py#L105) and modifying the [generation function](https://github.com/edwko/OuteTTS/blob/d90c645f56c9567ba91bea15f63950320e422ea7/outetts/v0_1/interface.py#L131) to retrieve prompts from the API. 
I’ll also look into adding support soon for LMStudio, Ollama, Llama.cpp server, and potentially other APIs.

**Comment by tushar-31093** [comment]
Also, is there generation slow? For example, I have an LLM agent at my end with a local machine with 6GB GPU. I simply setup the library as I could and tried linking the LLM and this. The latency is huge from when it gets the response from the LLM and when it generates an audio response.

**Comment by edwko** [comment]
> Also, is there generation slow? For example, I have an LLM agent at my end with a local machine with 6GB GPU. I simply setup the library as I could and tried linking the LLM and this. The latency is huge from when it gets the response from the LLM and when it generates an audio response.

It’s likely that the GPU is struggling to handle both your LLM and this TTS model simultaneously. A 6GB GPU is on the lower end and may not have enough memory or compute power to run both efficiently. How are the results if you run only the TTS model on `llama.cpp`?

**Comment by tushar-31093** [comment]
Nope. It's the same. A lot of latency.
