### ISSUE TITLE
[Typo] Blog Link

### ISSUE THREAD

**Issue by SapphireLab** [edwko/OuteTTS#14]
I can't access the website correctly when I click the blog link in the README.
So I checked the official website and found the link appears to be case-sensitive.
It should be `https://www.outeai.com/blog/outetts-0.1-350m` 
rather than `https://www.outeai.com/blog/OuteTTS-0.1-350M`.

**Comment by edwko** [comment]
Fixed it. Now you can use both links. Thanks for letting me know!
