### ISSUE TITLE
RuntimeError: Calculated padded input size per channel: (6). Kernel size: (7). Kernel size can't be greater than actual input size

### ISSUE THREAD

**Issue by profitgrowinginnovator** [edwko/OuteTTS#16]
I always get:
RuntimeError: Calculated padded input size per channel: (6). Kernel size: (7). Kernel size can't be greater than actual input size

Here is the code. I tried both load_speaker and create_speaker
from outetts.v0_1.interface import InterfaceHF, InterfaceGGUF

# Initialize the Hugging Face model
model_name = "OuteAI/OuteTTS-0.1-350M"

interface = InterfaceHF(model_name)

# Define your input text
text = "Hello world. How are you doing? Let's hope this works..."

# Initialize the speaker from a file
#speaker = interface.load_speaker("maarten.pkl")

speaker = interface.create_speaker(
    "voice.wav",
    "Filler text (also placeholder text or dummy text) is text that shares some characteristics of a real written text, but is random or otherwise generated. It may be used to display a sample of fonts, generate text for testing, or to spoof an e-mail spam filter. The process of using filler text is sometimes called greeking, although the text itself may be nonsense, or largely Latin, as in Lorem ipsum."
)

# Generate TTS output
output = interface.generate(
    text=text,
    speaker=speaker,
    temperature=0.1,
    repetition_penalty=1.1,
    max_length=4096  # Ensure this matches or exceeds the length of your input
)

# Play the generated audio
output.play()

# Save the generated audio to a file
output.save("output.wav")

**Comment by edwko** [comment]
This issue occurs when `get_audio` produces an empty output, which means it was unable to find audio tokens. This can happen if your speaker input is too long and exceeds the context length of 4096, or if the model returns `EOS` token too early. I suggest using a shorter speaker input, ideally between 5-15 seconds. I’ll implement a fix soon that will display an error message when audio generation fails due to empty output.

**Comment by mectors** [comment]
Thanks for clarifying. My audio was long so will try with a shorter one.

**Comment by profitgrowinginnovator** [comment]
Just to confirm that a shorter audio worked. Thanks for the help.
