### ISSUE TITLE
Cloned voice is not close to the original

### ISSUE THREAD

**Issue by nitinmukesh** [edwko/OuteTTS#19]
Not getting good cloned voice. Any suggestions, plz.

Reference

https://github.com/user-attachments/assets/62706771-7628-49c6-a797-f54e712555d4

Pickle 

[speaker.zip](https://github.com/user-attachments/files/17715886/speaker.zip)

Cloned output

https://github.com/user-attachments/assets/3841086b-609f-4eb9-a073-ea854ee8ae14

```
# Load the speaker from a file
speaker = interface.load_speaker("speaker.pkl")

# Generate TTS with the custom voice
output = interface.generate(
    text="This is a cloned voice speaking",
    speaker=speaker,
    temperature=0.1,
    repetition_penalty=1.1,
    max_length=4096
)
output.save("cloned.wav")
```

**Comment by edwko** [comment]
If the speaker sample is too unfamiliar to the model, it may struggle to produce an accurate clone, as this is still an early version trained on a limited dataset. You might try adjusting the temperature to a higher value, like 0.6-0.8, which could help a bit. The next release will address current limitations and is expected to improve voice cloning.

**Comment by zoldaten** [comment]
there's have a work to do ))
before:
[voice2.zip](https://github.com/user-attachments/files/17957303/voice2.zip)
after:
[output2.zip](https://github.com/user-attachments/files/17957313/output2.zip)
