### ISSUE TITLE
Windows permission issue

### ISSUE THREAD

**Issue by AWAS666** [edwko/OuteTTS#2]
For some reason I'm getting an permission error on the temp file this creates when using the voice cloning.
https://github.com/edwko/OuteTTS/blob/bb7ec58a414497e6342feda857d5c7141fd417c4/outetts/v0_1/interface.py#L58

Overwriting this tempfile name with "test.wav" to have it in my local dir fixed it for me.

Also wouldn't it be better to have an option to cache this instead of resampling it every time?

Fun model though, has some potential once it has a higher parameter/higher bitrate version, good job 👍

**Comment by razvanab** [comment]
You mean replacing ` (suffix=".wav") ` with  `(suffix="test.wav")`  ?

**Comment by AWAS666** [comment]
No I replaced the entire temp file name with a local file, not sure myself what is going on there

**Comment by edwko** [comment]
I've removed the use of the temporary file in the latest update, so you shouldn't encounter this error anymore.

To update, run:

```bash
pip install outetts --upgrade
```

I've also added support for saving and loading speakers.

```python
interface.save_speaker(speaker, "speaker.pkl")
```

and load it back later with:

```python
speaker = interface.load_speaker("speaker.pkl")
```
