### ISSUE TITLE
program crashed if I run official code, how can i fix it?

### ISSUE THREAD

**Issue by bobo-wmdigit** [edwko/OuteTTS#21]
![WX20241119-122416](https://github.com/user-attachments/assets/702d1bd4-e831-4e27-b920-2d6b68e56549)
log info is shown in the picture
thanks for your help.

**Comment by edwko** [comment]
Hey, 
Could you please post the full error message and the exact code you’re trying to run?

**Comment by hadamard-2** [comment]
@bobo-wmdigit I encountered similar warnings, and what worked for me was using a much shorter text, like: '_The quick brown fox jumps over the lazy dog._'
I could be wrong, but my best guess is that the warnings, combined with the long generation time, might have given the illusion that the program had crashed when it actually hadn’t.

**Comment by bobo-wmdigit** [comment]
> Hey, Could you please post the full error message and the exact code you’re trying to run?



> @bobo-wmdigit I encountered similar warnings, and what worked for me was using a much shorter text, like: '_The quick brown fox jumps over the lazy dog._' I could be wrong, but my best guess is that the warnings, combined with the long generation time, might have given the illusion that the program had crashed when it actually hadn’t.

Thanks for your reply. I’ve resolved the issue—it turned out the repository only supports Python 3.9.
