### ISSUE TITLE
Does it support Chinese?

### ISSUE THREAD

**Issue by johnny8353** [edwko/OuteTTS#23]
when I try generate Chinese,It raise error:
RuntimeError: Calculated padded input size per channel: (6). Kernel size: (7). Kernel size can't be greater than actual input size

output = interface.generate(
    text="你好.",
    temperature=0.1,
    repetition_penalty=1.1,
    max_length=4096
)

Does it support Chinese?

**Comment by edwko** [comment]
Version 0.1 currently supports only English. The next release is planned to include additional languages, including Chinese.

**Comment by edwko** [comment]
@platform-kit Many versions ahead now, check the latest one: https://huggingface.co/OuteAI/Llama-OuteTTS-1.0-1B

Supports: English, Arabic, Chinese, Dutch, French, German, Italian, Japanese, Korean, Lithuanian, Russian, Spanish, Portuguese, Belarusian, Bengali, Georgian, Hungarian, Latvian, Persian/Farsi, Polish, Swahili, Tamil, Ukrainian
