### ISSUE TITLE
Can the model support Chinese？

### ISSUE THREAD

**Issue by fancysh** [edwko/OuteTTS#25]
Hello! On the official website, I saw a model called OuteTTS-0.2-500M which can be configured for language settings. However, I couldn't find detailed documentation on Hugging Face. Also, the installation command for both models is pip install outetts. Could you please provide more configuration details for this model? Thank you!
 
error message：
File "/User/demo/xxx.py", line 4, in <module>
    model_config = outetts.HFModelConfig_v1(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'outetts' has no attribute 'HFModelConfig_v1'

**Comment by edwko** [comment]
Yes! There was an issue with the model files, but it's now fixed. Give it a try! :)

**Comment by fancysh** [comment]
The audio generated using the system speaker is not very satisfactory; it still sounds more like foreign colloquial speech. Can the output be adjusted to produce stable and standard Chinese pronunciation? Additionally, the speakerId I used was trained on Chinese data, but the output contains mixed pronunciations from other countries. Are there specific parameters that can be set or adjusted for this? Could you provide a document detailing these settings? Thanks.
<img width="701" alt="企业微信截图_3598553c-1624-4e76-b664-9d67871f6892" src="https://github.com/user-attachments/assets/f4448849-fad0-43fb-8d90-568430449c08">
