### ISSUE TITLE
automatic reference text transcription

### ISSUE THREAD

**Issue by cocktailpeanut** [edwko/OuteTTS#28]
Currently the voice cloning feature doesn't seem to work unless you provide an accurate transcription of the reference audio, which is too tedious.

This can be fixed by incorporating whisper to automatically transcribe the reference audio instead of making the users manually enter the reference text. This would make a huge difference since most people are too lazy to transcribe audio clips

**Comment by edwko** [comment]
Thanks for the suggestion, I’ll look into adding this.

**Comment by edwko** [comment]
Added in the 0.2.1 release :)
