### ISSUE TITLE
Could I run this in the browser?

### ISSUE THREAD

**Issue by flatsiedatsie** [edwko/OuteTTS#30]
Any tips on running this with Javascript inside a web browser?

As an experiment I tried running the GGUF version with [Wllama](https://github.com/ngxson/wllama), and `I like big books` resulted in the generation of a list that looks like:

```
- 10000
- 10000
- 10000
- 10000
- 10000
- 10000
- 10000
- 10000
- 10000
- 10000
- 10000
- 10000
- etc
```

I imagine that's a list of float values of a wav file? But it generated that list at about 1 number per second.

**Comment by edwko** [comment]
It sounds like you might be passing plain input, the inputs need to be structured properly for an audio prompt. You can check out this reference:  
[prepare_prompt](https://github.com/edwko/OuteTTS/blob/4c9c3dd4c1b31acaa1b732402d831501810b04a1/outetts/version/v1/interface.py#L118C1-L118C63)

Additionally, when you get the output, you’ll need to convert the tokens back into audio. You can refer to this:  
[get_audio](https://github.com/edwko/OuteTTS/blob/4c9c3dd4c1b31acaa1b732402d831501810b04a1/outetts/version/v1/interface.py#L126)

**Comment by flatsiedatsie** [comment]
Ah, ok. So does that mean I would need a Javascript version of the tokenizer and de-tokenizer?

Could you point me in a direction on how to create that?

**Comment by xenova** [comment]
@flatsiedatsie Tadaah 🥳 https://github.com/edwko/OuteTTS/pull/42

**Comment by flatsiedatsie** [comment]
Amazing as always
