### ISSUE TITLE
Cant install: Python version error

### ISSUE THREAD

**Issue by rosmur** [edwko/OuteTTS#31]
When on Python 3.12, I get the error:

`RuntimeError: Cannot install on Python version 3.12.7; only versions >=3.6,<3.10 are supported.
`

When I try on Python 3.9, I get the error:
```
 uv pip install outetts   
  × No solution found when resolving dependencies:
  ╰─▶ Because the current Python version (3.9.6) does not satisfy Python>=3.10 and all versions of outetts depend on Python>=3.10, we can
      conclude that all versions of outetts cannot be used.
      And because only the following versions of outetts are available:
          outetts==0.1.3
          outetts==0.1.4
          outetts==0.1.5
          outetts==0.1.6
          outetts==0.1.7
          outetts==0.2.0
      and you require outetts, we can conclude that your requirements are unsatisfiable.
```

**Comment by guidov** [comment]
The installation worked with python==3.11 for me but not python==3.12
I did not use uv, instead I used a conda environment (with cpu). You could use pyenv also .

git clone https://github.com/edwko/OuteTTS.git
cd OuteTTS/
conda create -n outetts python==3.11
conda activate outetts
pip install llama-cpp-python   --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu
pip install huggingface-hub
pip install -r requirements.txt
