### ISSUE TITLE
Audio Output Gets Cut Off at the End

### ISSUE THREAD

**Issue by Meshwa428** [edwko/OuteTTS#45]
Hello,  

I’ve encountered an issue where the audio output seems to get cut off at the end of text sequences.  

Instead of a smooth, natural conclusion to the generated audio, it feels like the audio either isn’t being fully generated or is getting truncated. This can make the outputs sound abrupt or incomplete, especially for longer/very short sequences or ones that would normally have a more gradual ending.  

**Steps to Reproduce**:  
1. Use OuteTTS to generate audio for a relatively long/small text sequence.  
2. Observe the ending of the generated audio file.  
3. Note that the last part of the audio feels cut off or truncated.
4. Input text used: `uhm, who are you by the way?`

See the output audio below
https://github.com/user-attachments/assets/b2c24d61-93c6-4273-ac9f-978b472e8f73

Notice that the last word `way?` is being cut off is this an expected behaviour or it wasn't planed?

**Expected Behavior**:  
The generated audio should have a smooth and natural conclusion, matching the style and pace of the preceding content.  

**Environment Details**:  
- Library version: `v0.2.1`
- Python version: `Python 3.11.4`
- OS: `Windows 11`
- Model being used: `OuteAI/OuteTTS-0.2-500M`

**Additional Notes**:  
If there’s any debug or additional logs you’d like me to provide, I’d be happy to help. Let me know if you need further details to investigate the issue.  

Thank you for looking into this!

**Comment by edwko** [comment]
Are you using any speaker reference or not, and what backend are you using? This seems to work fine on my end. Could you share the code you're running?

**Comment by edwko** [comment]
Could try to increase the temperature a bit. Since the model was trained on only Latin characters, it doesn't have a clear understanding of punctuation, which might cause quick endings depending on the generation. This should improve in future versions as I'm planning to add support for special characters.

**Comment by Meshwa428** [comment]
Here is my code snippet:
```py
import outetts

# Configure the model
model_config = outetts.HFModelConfig_v1(
    model_path="OuteAI/OuteTTS-0.2-500M",
    language="en",  # Supported languages in v0.2: en, zh, ja, ko
)

# Initialize the interface
interface = outetts.InterfaceHF(model_version="0.2", cfg=model_config)

# Load speaker profile
speaker = interface.load_default_speaker(name="female_2")


while True:
    input_text = input("Enter Text: ")
    if input_text == "!exit":
        break
    output = interface.generate(
        text=input_text,
        temperature=0.6,
        repetition_penalty=1.1,
        max_length=4096,
        speaker=speaker,
    )

    output.save("output.wav")
    output.play()
```

**Comment by Meshwa428** [comment]
> Could try to increase the temperature a bit. Since the model was trained on only Latin characters, it doesn't have a clear understanding of punctuation, which might cause quick endings depending on the generation. This should improve in future versions as I'm planning to add support for special characters.

okay, i tried removing punctuations and still the model's output gets cut off at the end, the last second of the generated audio seems to be getting cut off

**Comment by Meshwa428** [comment]
okay identified the problem. the play method is cutting the audio, i tried to play the saved audio and it played the full audio with the last 0.5 secs but the play method of output didn't.

**Comment by edwko** [comment]
> okay, i tried removing punctuations

You don't need to remove punctuation yourself, the library handles text processing you can see the function here: [process_text](https://github.com/edwko/OuteTTS/blob/8f5f510fa4683d62b03f951fc710937a9142f2b0/outetts/version/v1/prompt_processor.py#L39)

> okay identified the problem. the play method is cutting the audio, i tried to play the saved audio and it perfectly played the full audio with the last 0.5 secs but the play method of output didn't.

Great that you found the issue! It could be a compatibility problem between `sounddevice` and your hardware since that's the library used for audio playback. I should probably add other playback backends to the library.

**Comment by edwko** [comment]
Added `Add support for multiple audio playback backends (sounddevice, pygame...)` to the roadmap. Will have the ability to switch between playback libraries.
