### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by kristaller486** [edwko/OuteTTS#7]
Thanks for your work! Are you planning to release a training code? I'd like to try to adapt this model to my language.

**Comment by yukiarimo** [comment]
Same. I have 30h+ ultra high-quality expressive dataset and would like to train/fine-tune your model to see how it goes!

**Comment by JohnHerry** [comment]
> The model can be trained just like any other language model, you can use any of your preferred training tools for next-token prediction or supervised fine-tuning.
> 
> Currently, there isn’t a specific example for data processing, but I plan to add one in the future to make this easier. In the meantime, you can generate prompts using the interface functions provided in the code:
> 
> * [get_completion_prompt](https://github.com/edwko/OuteTTS/blob/c33e87023361096594b762e1c5bbc91b16b4244c/outetts/v0_1/prompt_processor.py#L47)
> * [create_speaker](https://github.com/edwko/OuteTTS/blob/c33e87023361096594b762e1c5bbc91b16b4244c/outetts/v0_1/interface.py#L52)
> 
> Make sure to add both the `audio_end` and `eos + "\n"` tokens at the end of each sample.

want to learn more about this project. Is it a project just like [TortoiseTTS](https://github.com/neonbjb/tortoise-tts) with a speech tokenizer and a GPT like token llm? what is the specific advance?  speedup？ or stability?
